blueprint:
  name: Moes 4-Button Controller
  description: Handle events for the 4-button remote.
  domain: automation
  input:
    target_device:
      name: Button
      selector:
        device:
          integration: smartthings
    main_pushed:
      name: Main Button - Pushed
      default: []
      selector: {action: {}}
    main_double:
      name: Main Button - Double
      default: []
      selector: {action: {}}
    main_held:
      name: Main Button - Held
      default: []
      selector: {action: {}}
    btn2_pushed:
      name: Button 2 - Pushed
      default: []
      selector: {action: {}}
    btn2_double:
      name: Button 2 - Double
      default: []
      selector: {action: {}}
    btn2_held:
      name: Button 2 - Held
      default: []
      selector: {action: {}}
    btn3_pushed:
      name: Button 3 - Pushed
      default: []
      selector: {action: {}}
    btn3_double:
      name: Button 3 - Double
      default: []
      selector: {action: {}}
    btn3_held:
      name: Button 3 - Held
      default: []
      selector: {action: {}}
    btn4_pushed:
      name: Button 4 - Pushed
      default: []
      selector: {action: {}}
    btn4_double:
      name: Button 4 - Double
      default: []
      selector: {action: {}}
    btn4_held:
      name: Button 4 - Held
      default: []
      selector: {action: {}}

variables:
  # Captures the internal Home Assistant Device ID from the UI dropdown
  selected_ha_device: !input target_device

trigger:
  - platform: event
    event_type: smartthings.button

condition:
  - condition: template
    # Extracts the SmartThings UUID from the device registry and matches it against the incoming event
    value_template: "{{ trigger.event.data.device_id in device_attr(selected_ha_device, 'identifiers') | string }}"

action:
  - choose:
      - conditions: "{{ trigger.event.data.component_id == 'main' }}"
        sequence:
          - choose:
              - conditions: "{{ trigger.event.data.value == 'pushed' }}"
                sequence: !input main_pushed
              - conditions: "{{ trigger.event.data.value == 'double' }}"
                sequence: !input main_double
              - conditions: "{{ trigger.event.data.value == 'held' }}"
                sequence: !input main_held
      - conditions: "{{ trigger.event.data.component_id == 'button2' }}"
        sequence:
          - choose:
              - conditions: "{{ trigger.event.data.value == 'pushed' }}"
                sequence: !input btn2_pushed
              - conditions: "{{ trigger.event.data.value == 'double' }}"
                sequence: !input btn2_double
              - conditions: "{{ trigger.event.data.value == 'held' }}"
                sequence: !input btn2_held
      - conditions: "{{ trigger.event.data.component_id == 'button3' }}"
        sequence:
          - choose:
              - conditions: "{{ trigger.event.data.value == 'pushed' }}"
                sequence: !input btn3_pushed
              - conditions: "{{ trigger.event.data.value == 'double' }}"
                sequence: !input btn3_double
              - conditions: "{{ trigger.event.data.value == 'held' }}"
                sequence: !input btn3_held
      - conditions: "{{ trigger.event.data.component_id == 'button4' }}"
        sequence:
          - choose:
              - conditions: "{{ trigger.event.data.value == 'pushed' }}"
                sequence: !input btn4_pushed
              - conditions: "{{ trigger.event.data.value == 'double' }}"
                sequence: !input btn4_double
              - conditions: "{{ trigger.event.data.value == 'held' }}"
                sequence: !input btn4_held
