blueprint:
  name: Moes 4-Button Controller
  description: Handle events for the 4-button remote.
  domain: automation
  input:
    button_device:
      name: Device
      selector:
        device:
          integration: smartthings
    button_1_action:
      name: Button 1 (Main) Action
      default: []
      selector: {action: {}}
    button_2_action:
      name: Button 2 Action
      default: []
      selector: {action: {}}
    button_3_action:
      name: Button 3 Action
      default: []
      selector: {action: {}}
    button_4_action:
      name: Button 4 Action
      default: []
      selector: {action: {}}

trigger:
  - platform: event
    event_type: smartthings.button

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_id == inputs.button_device }}"

action:
  - choose:
      - conditions: "{{ trigger.event.data.component_id == 'main' }}"
        sequence: !input button_1_action
      - conditions: "{{ trigger.event.data.component_id == 'button2' }}"
        sequence: !input button_2_action
      - conditions: "{{ trigger.event.data.component_id == 'button3' }}"
        sequence: !input button_3_action
      - conditions: "{{ trigger.event.data.component_id == 'button4' }}"
        sequence: !input button_4_action
